### ISSUE TITLE
Update Readme.md file with Screenshots

### ISSUE THREAD

**Issue by SAITARUN55** [enzaimz/c_made_easy#21]
@harry-hov Please assign this task to me bro

**Comment by harry-hov** [comment]
P.S.- Your contribution won't be count until coding period begins.

**Comment by SAITARUN55** [comment]
From today the coding period begins right? @harry-hov

**Comment by harry-hov** [comment]
Yep.. my bad @SAITARUN55

**Comment by SAITARUN55** [comment]
Okay cool
