### ISSUE TITLE
Add Contributors Section Page

### ISSUE THREAD

**Issue by harry-hov** [enzaimz/c_made_easy#3]
The app must contain the name of all the contributors with their github username.

**Comment by aitorres** [comment]
Hello @harry-hov! I can take this issue. I'm thinking of automatically fetching contributors of this repo using Github's Public API. Is that okay?

**Comment by harry-hov** [comment]
go for it @aitorres

**Comment by satyamroy001** [comment]
I want to join as a kwoc contributor.

**Comment by harry-hov** [comment]
Start sending Pull Requests once the coding period begins. @satyamroy001
