### ISSUE TITLE
Add more content in array.dart file

### ISSUE THREAD

**Issue by udaymewada** [enzaimz/c_made_easy#30]
Present array.dart doesn't contain enough information about Array in C, do add more information about ARRAY IN C so that it will be easier for the reader to understand.

**Comment by Gauravmauryaios** [comment]
I would like to work on it. Please assign this to me.

**Comment by abhitidarbar** [comment]
> I would like to work on it. Please assign this to me.

Hey , @Gauravmauryaios I apologise but I think this issue has been addressed could you please check out other issues. A similar issue to this one is #43 . Or you can create an issue of your own and start working on it.
