### ISSUE TITLE
Improve Content

### ISSUE THREAD

**Issue by harry-hov** [enzaimz/c_made_easy#4]
Improve the content available in the App.
It must be easy to understand for beginners.

**Comment by zarszz** [comment]
Hi sir,
How about to add several application photos in the markdown ??

**Comment by harry-hov** [comment]
Hi @zarszz !!
can you pls explain, what do you mean by application photos?
P.S. - you can call me by my name.

**Comment by zarszz** [comment]
umm, maybe like photos or screenshot when the application running

**Comment by harry-hov** [comment]
photos or screenshots of what ?

**Comment by sivaram16** [comment]
Shall I work on this issue? Can you assign me?
Will Improve all the content of the fuctions of the C detaily.

**Comment by harry-hov** [comment]
Yeah, sure @ThalapathySiva

**Comment by sivaram16** [comment]
I have done my PR .

**Comment by harry-hov** [comment]
Kindly Sorry for the delay. 
Due to Diwali (Festival in India) review is getting delayed. We'll try our best to get your PR reviewed asap @ThalapathySiva

**Comment by sivaram16** [comment]
It's okay bro...!! Advance Happy diwali 
Hactoberfest end is nearing so that's why I reminded... no problem
