### ISSUE TITLE
Replace "About Developer" page with "Contributors"

### ISSUE THREAD

**Issue by harry-hov** [enzaimz/c_made_easy#42]
**Problem Description**
Current 'About Developer' page in Drawer only show the 2 contributors. Which kinda sucks. 
Can we replace that page with list of all the contributors?

**Describe the solution you'd like**
Possible solution I can think of is to fetch the contributors directly from the GitHub.

**Describe alternatives you've considered**
Alternatively you can hard code all the Contributors. But I wouldn't recommend that.

**Comment by savagecarol** [comment]
ya there is one thing you can hit the api of the git repo (github can provide that) and can take the names of the the people who are present in that particular repository .

**Comment by harry-hov** [comment]
yeah @savagecarol. 
I guess this will do the trick: "curl https://api.github.com/repos/enzaimz/c_made_easy/contributors"

**Comment by savagecarol** [comment]
cool assign it to me i will do that

**Comment by savagecarol** [comment]
assign it to me

**Comment by savagecarol** [comment]
i think we should remove contributors any one page from (contributors , about developer)

**Comment by savagecarol** [comment]
it is done so can i work on other now?

**Comment by abhitidarbar** [comment]
> it is done so can i work on other now?

Yes you can
