### ISSUE TITLE
Change the name of seventh point from "control statements" to "jump statements" in theory.dart

### ISSUE THREAD

**Issue by abhitidarbar** [enzaimz/c_made_easy#45]
As control statement basically tells us the order in which the instructions in a program must be executed. And there are four types of control statements in C:
Decision making statements-  if ,if else etc
Selection statements- switch case
Iteration statements- loops
Jump statements- break ,continue etc
The name should be changed to "jump statements" so that users can get precise information.

**Comment by aryanharitsh123** [comment]
I would like to work on this issue.

**Comment by abhitidarbar** [comment]
> I would like to work on this issue.
Done .

**Comment by aryanharitsh123** [comment]
Should I rename the controlbasic.dart to jumpstatement.dart or leave it as it is?  I have to modify it to change the title in the jump statement screen.

**Comment by abhitidarbar** [comment]
> Should I rename the controlbasic.dart to jumpstatement.dart or leave it as it is? I have to modify it to change the title in the jump statement screen.

I will suggest to leave it as it is because this file is mentioned in other files which will probably create error or even if you change the name in other files too it will probably create a merge conflict if someone else is working in that file. So, it will be best for now to leave it as it is.

**Comment by aryanharitsh123** [comment]
Check this PR, please.
https://github.com/enzaimz/c_made_easy/pull/48
