### ISSUE TITLE
Add information in switchcase.dart

### ISSUE THREAD

**Issue by abhitidarbar** [enzaimz/c_made_easy#46]
At least one example of switch case should be added for better understanding

**Comment by aryanharitsh123** [comment]
I would like to work on this. Assign this to me please.

**Comment by abhitidarbar** [comment]
> I would like to work on this. Assign this to me please.

Done 👍

**Comment by aryanharitsh123** [comment]
Is this example fine? Or should I add something else?
![example_switch](https://user-images.githubusercontent.com/37960580/101523957-513dd980-39af-11eb-915e-29f1708c120b.jpg)

**Comment by abhitidarbar** [comment]
> Is this example fine? Or should I add something else?
> ![example_switch](https://user-images.githubusercontent.com/37960580/101523957-513dd980-39af-11eb-915e-29f1708c120b.jpg)

Looks fine to me .

**Comment by aryanharitsh123** [comment]
https://github.com/enzaimz/c_made_easy/pull/52
Merge please, If this looks fine.
