### ISSUE TITLE
Delete the information about switch case from looping.dart

### ISSUE THREAD

**Issue by abhitidarbar** [enzaimz/c_made_easy#47]
As there are only three types of loop and switch is not a loop, also there is a complete another dart file for switch i.e switchcase.dart. We don't need it here.

**Comment by vivekgugnani** [comment]
> As there are only three types of loop and switch is not a loop, also there is a complete another dart file for switch i.e switchcase.dart. We don't need it here.

I would like to work on this issue.

**Comment by aryanharitsh123** [comment]
Handled this issue in the last PR.
https://github.com/enzaimz/c_made_easy/pull/48/commits
