### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by harry-hov** [enzaimz/c_made_easy#5]
Add Instructions to setup the project.

**Comment by aquibbaig** [comment]
Can take this up!

**Comment by harry-hov** [comment]
Sure @aquibbaig

**Comment by udaymewada** [comment]
Done!!
@harry-hov

**Comment by aquibbaig** [comment]
@udaymewada Congrats on your contribution but well, you shouldn't! Meaning no harm or offence the moral side of Open source says you shouldn't work on issues which are assigned until the person assigned is not working on it anymore. As you can see it was already assigned to me.

**Comment by harry-hov** [comment]
Indeed you are right @aquibbaig. Apologises for your inconvenience.
If you have started working on this issue, you can keep on working. Please let me know your progress so far.

Im marking @udaymewada's PR for Reviewing later.

**Comment by aquibbaig** [comment]
It's fine! @harry-hov . Let me just find other issues. No problem!

**Comment by harry-hov** [comment]
Superseeded by #13
