### ISSUE TITLE
Text Not Visible during Light Theme

### ISSUE THREAD

**Issue by infiniteoverflow** [enzaimz/c_made_easy#56]
**Describe the bug**
When we turn on Light Mode in the App , the texts in the Theory Sections is not visible as the text color remains as white which is not seen as the background also becomes white.

**To Reproduce**
1. Go to the App bar
2. Turn on Light Mode
3. Open any one section in the Theory list

**Expected behavior**
A darker text color in light mode

**Screenshot**
<img width="370" alt="Screenshot 2020-12-09 at 3 06 31 PM" src="https://user-images.githubusercontent.com/40236624/101611953-2182e600-3a30-11eb-9839-6fa91bcd8920.png">

**Comment by abhitidarbar** [comment]
@infiniteoverflow are you working on this issue ?

**Comment by abhitidarbar** [comment]
@infiniteoverflow are u still working on this.

**Comment by Saransh-cpp** [comment]
Hi there! I'd like to work on this issue.
