### ISSUE TITLE
Adding Info about multidimesional arrays in arrays.dart

### ISSUE THREAD

**Issue by aryanharitsh123** [enzaimz/c_made_easy#57]
Array.dart only contains information, examples, and initialization of 1-dimensional arrays. It would be better if it contains info about multidimensional arrays and more examples.

**Comment by abhitidarbar** [comment]
> Arrays.dart only contains information, examples, and initialization of 1-dimensional arrays. It would be better if it contains info about multidimensional arrays and more examples.

@aryanharitsh123 the filename is "array.dart" and not "arrays.dart". These minor mistakes should be kept in mind.

**Comment by aryanharitsh123** [comment]
Okay, I will keep that in mind.
Can you please confirm if this is fine or should I add more info. ?
![Array2](https://user-images.githubusercontent.com/37960580/101818078-5df63500-3b49-11eb-905d-45d47b5ebedf.jpg)

**Comment by abhitidarbar** [comment]
@aryanharitsh123 I think this is fine for now.
