### ISSUE TITLE
Add information about pointers in C

### ISSUE THREAD

**Issue by abhitidarbar** [enzaimz/c_made_easy#60]
Our app needs to contain information about pointers which is an essential part of C programming language.

**Comment by aryanharitsh123** [comment]
I would like to work on this.

**Comment by aryanharitsh123** [comment]
I have added some info. about pointers and a program for it. Review these changes,
![Program](https://user-images.githubusercontent.com/37960580/101870767-48fcbe80-3ba8-11eb-9de7-1deb1e9811e5.jpg)
 please. 
![Main](https://user-images.githubusercontent.com/37960580/101870741-3d10fc80-3ba8-11eb-94b7-642e652edd8c.jpg)
![content](https://user-images.githubusercontent.com/37960580/101870752-400bed00-3ba8-11eb-8ef9-708c5332fe0b.jpg)
![content 2](https://user-images.githubusercontent.com/37960580/101870756-4306dd80-3ba8-11eb-9882-5ab07c330328.jpg)

**Comment by abhitidarbar** [comment]
Hey @aryanharitsh123 the current information looks fine. Can we also include the information about some important types of pointer like void pointer, dangling pointer, far pointer, near pointer, etc.

**Comment by aryanharitsh123** [comment]
Okay, I'll add them too.

**Comment by aryanharitsh123** [comment]
Added Info. about some more types of pointers. Please Review.
![1607699567979](https://user-images.githubusercontent.com/37960580/101920334-ad903b80-3bf1-11eb-9667-10df7b093b88.jpg)
![1607699567986](https://user-images.githubusercontent.com/37960580/101920339-af59ff00-3bf1-11eb-8273-e25616cb0aac.jpg)
![1607699567991](https://user-images.githubusercontent.com/37960580/101920344-b08b2c00-3bf1-11eb-9002-2c872476a148.jpg)

**Comment by abhitidarbar** [comment]
@aryanharitsh123 Its great. Good job!

**Comment by aryanharitsh123** [comment]
https://github.com/enzaimz/c_made_easy/pull/64
Done, Please Review and Merge.
