### ISSUE TITLE
Add more programs 

### ISSUE THREAD

**Issue by anushkasinghal11** [enzaimz/c_made_easy#61]
Add more programs in C language

**Comment by anushkasinghal11** [comment]
Please assign this issue to me

**Comment by Siddhant-K-code** [comment]
I wanted to add more C programs, Can I add `Data Structure & Algorithms` ( *can a make a new section for that* ) `Implementations in C` ?

**Comment by abhitidarbar** [comment]
> I wanted to add more C programs, Can I add `Data Structure & Algorithms` ( _can a make a new section for that_ ) `Implementations in C` ?

But only add Data Structures and Algorithms in C. Don't make a new section. Just make it like this Programs > data structure > list of data structures > implementation code .
For Example : User clicks on programs > data structures > linked list > program code for linked list.

**Comment by aryanharitsh123** [comment]
I have added Info. and Implementation of Linked list, Stacks, and Queue. Please review.


![1608399099196](https://user-images.githubusercontent.com/37960580/102695624-93d4a100-424e-11eb-9410-8a4530b295ee.jpg)
![1608399099210](https://user-images.githubusercontent.com/37960580/102695627-959e6480-424e-11eb-83d9-3258a5b20d5a.jpg)
![1608399099218](https://user-images.githubusercontent.com/37960580/102695629-9636fb00-424e-11eb-8541-48f6b39adf16.jpg)
![1608399099227](https://user-images.githubusercontent.com/37960580/102695630-96cf9180-424e-11eb-88a1-34921c5c3d98.jpg)
![1608399099234](https://user-images.githubusercontent.com/37960580/102695632-9800be80-424e-11eb-8f4c-5309a07b6d6c.jpg)

**Comment by abhitidarbar** [comment]
you can also add a  basic program for tree and graph.

**Comment by aryanharitsh123** [comment]
Okay, I'll do it.

**Comment by aryanharitsh123** [comment]
Added them.
![1608404494639](https://user-images.githubusercontent.com/37960580/102697308-e0be7480-425a-11eb-8387-9f513e47b926.jpg)
![1608404494657](https://user-images.githubusercontent.com/37960580/102697309-e2883800-425a-11eb-8de2-aa93ee455293.jpg)
![1608404494649](https://user-images.githubusercontent.com/37960580/102697311-e3b96500-425a-11eb-82e5-efba0cfb2ace.jpg)

**Comment by aryanharitsh123** [comment]
Added them.
![1608404494657](https://user-images.githubusercontent.com/37960580/102697333-08add800-425b-11eb-9d09-bc65c4b75317.jpg)
![1608404494649](https://user-images.githubusercontent.com/37960580/102697334-0a779b80-425b-11eb-960f-77c421465999.jpg)

**Comment by abhitidarbar** [comment]
Good job make a pr
