### ISSUE TITLE
Adding Info. and some programs on Strings.

### ISSUE THREAD

**Issue by aryanharitsh123** [enzaimz/c_made_easy#65]
There should be a dedicated section on Strings in theory and some programs for better understanding.

**Comment by aryanharitsh123** [comment]
I have added some info. on Strings, I think we should also add some info about how to read strings, how to pass them through functions. So, should I add all that on the theory page? or make separate programs for them
![1607792304622](https://user-images.githubusercontent.com/37960580/101989970-e3a0ee80-3cc9-11eb-8db9-a981f0859dcc.jpg)
![1607792304610](https://user-images.githubusercontent.com/37960580/101989973-e69bdf00-3cc9-11eb-9ae5-a2b4e4707787.jpg)
![1607792304616](https://user-images.githubusercontent.com/37960580/101989991-fc110900-3cc9-11eb-9032-7feaac802e1d.jpg)


?

**Comment by abhitidarbar** [comment]
@aryanharitsh123 If you think that you can explain it theoretically with less lines of codes you should add it here. But if you are explaining it through programs you should add them in programs.

**Comment by aryanharitsh123** [comment]
It would be more convenient to explain them through programs.

**Comment by abhitidarbar** [comment]
Then just add them under programs section with relevant self explanatory names of programs.

**Comment by harry-hov** [comment]
@aryanharitsh123 you can also redirect to those program from `strings.dart` page. And thanks for working on Strings.

**Comment by aryanharitsh123** [comment]
@harry-hov @abhitidarbar Should I add all of the programs in a single .dart file under programs folder ? Or seperate .dart for each program ?

**Comment by abhitidarbar** [comment]
@aryanharitsh123 you could do it just the way u did it in pointers.

**Comment by aryanharitsh123** [comment]
I have added these programs and there was a numbering issue in the main menu when I added pointers, I have fixed it now. Please review. 
![1607860610762](https://user-images.githubusercontent.com/37960580/102011250-11894000-3d69-11eb-97de-48b0a7cda089.jpg)
![1607860610768](https://user-images.githubusercontent.com/37960580/102011254-12ba6d00-3d69-11eb-9534-8a58b1263ed9.jpg)
![1607860610774](https://user-images.githubusercontent.com/37960580/102011255-13eb9a00-3d69-11eb-87e5-d5bf1ad463d7.jpg)

**Comment by abhitidarbar** [comment]
@aryanharitsh123 your work looks great. Make a pr for review

**Comment by abhitidarbar** [comment]
@aryanharitsh123 Good Job 👍 .

**Comment by aryanharitsh123** [comment]
Thank You. :)
