### ISSUE TITLE
Programs and Theory in Sorted Manner

### ISSUE THREAD

**Issue by Siddhant-K-code** [enzaimz/c_made_easy#70]
**Is your feature request related to a problem? Please describe.**
The programs/theories should be sorted in Beginner's Friendly order in `lib/program.dart` or `lib/theory.dart`

**Describe the solution you'd like**
Manually Sorting

**Comment by abhitidarbar** [comment]
Hey, the programs and theory in alphabetical order makes no sense. We want the content to be sorted in such a manner that it could be understood by beginners. Like only after learning the scanf()  and printf() you can learn further loops, pointers, etc right? So, I think it should be the way it is.

**Comment by Siddhant-K-code** [comment]
>  We want the content to be sorted in such a manner that it could be understood by beginners

Main Comment Updated

**Comment by abhitidarbar** [comment]
I think it is already sorted in the way it should be. Like I want to know where you are going with this sorting thing. Exactly what changes are you proposing.

**Comment by Siddhant-K-code** [comment]
i think, In, theory section it is sorted but, in `program.dart` it is just given as random !!

**Comment by abhitidarbar** [comment]
> i think, In, theory section it is sorted but, in `program.dart` it is just given as random !!

Okay you can start working on it
