### ISSUE TITLE
Adding Info, and programs related to Bitwise operators.

### ISSUE THREAD

**Issue by aryanharitsh123** [enzaimz/c_made_easy#74]
Bitwise operators are very useful when it comes to problem-solving, So, I guess there should be some info. and basic programs related to them.

**Comment by aryanharitsh123** [comment]
Should I add Bitwise operators inside the "operators in C" section or a separate section in the theory menu?

**Comment by abhitidarbar** [comment]
@aryanharitsh123 if you want to add only names and one line about bitwise operator mention them in operators in C but if you want to explain them with proper description you should make a new dart file.

**Comment by aryanharitsh123** [comment]
Okay, I'll make a seperate .dart file with explanation,examples and some programs.

**Comment by abhitidarbar** [comment]
Great 👍

**Comment by aryanharitsh123** [comment]
Added all this, Please review.
![Screenshot_2020-12-19-00-24-47-265_com example c_made_easy](https://user-images.githubusercontent.com/37960580/102650493-04b58380-4191-11eb-979f-bf0050aa2c5e.jpg)
![Screenshot_2020-12-19-00-24-37-527_com example c_made_easy](https://user-images.githubusercontent.com/37960580/102650500-067f4700-4191-11eb-8d13-56ae24d90f4e.jpg)
![Screenshot_2020-12-19-00-24-34-453_com example c_made_easy](https://user-images.githubusercontent.com/37960580/102650501-0717dd80-4191-11eb-83bb-9f1d75d1fbd5.jpg)
![Screenshot_2020-12-19-00-24-26-603_com example c_made_easy](https://user-images.githubusercontent.com/37960580/102650505-07b07400-4191-11eb-8be3-e3d76b41e782.jpg)
![Screenshot_2020-12-19-00-24-19-122_com example c_made_easy](https://user-images.githubusercontent.com/37960580/102650511-08e1a100-4191-11eb-82ba-9f34fc8a9c8f.jpg)

**Comment by abhitidarbar** [comment]
Wow, you are doing a great work. Keep it up 💯

**Comment by aryanharitsh123** [comment]
Thank You :), Please Review and Merge.
